### ISSUE TITLE
Invalid code when names have spaces

### ISSUE THREAD

**Issue by slimshader** [kyubuns/AnKuchen#1]
When game object in hierarchy have names like "Some Button" generated code template has

```
Button Some Button {get; set;}
```

which causes compliation errors. Simple that comes to mind is to a trim and replace whitespaces with "_" in the names before generating identifiers. Could provide a PR over the weenekend

**Comment by kyubuns** [comment]
Oh, you're right.
When variable names are created, they now replace all but the _ symbol with a space.
Try updating Packages/packages-lock.json by changing the relevant part to `b4fd64ec4c9e018e68c80a256916ef974c84f6b3`

**Comment by slimshader** [comment]
Just tested the fix and now generated the code is ok but it seems it does not actually replace spaces with "_" but just removes them meaning "Some Button" in hierarchy becomes "SomeButton" in the generated template.

**Comment by kyubuns** [comment]
I was torn between deleting the space or changing it to an underbar, but I prepared a version that would change it to an underbar.
`f7ad62eea88fa11a9c794b8a5042c37b48e24299`

I would have liked to be able to choose the option, but it's an auxiliary feature, so that's good.

**Comment by slimshader** [comment]
Fine for me either was as long as the generated code is fine :)

**Comment by kyubuns** [comment]
OK, this change will go into v1.1.0.
(If you are using PackageManager, you can use origin/master and it has already been applied.)
