### ISSUE TITLE
Possibilty to generate code template names without parent names

### ISSUE THREAD

**Issue by slimshader** [kyubuns/AnKuchen#2]
Currently when identifiers are generated, it is a concatation of the actual name and all predecessors so when having bunch of nested panels for layout purposes all names are combined in to single name, for example

Main Panel -> Bottom Panel -> Buy Unit Button

produces

```
Button MainPanelBottomPanelBuyUnitButton {get; set;}
```

would be useful if there was an option for templete generation to "omit parent names" so that generated code only contained

```
Button BuyUnitButton {get; set;}
```

**Comment by kyubuns** [comment]
I checked and it was a bug because it was behaving differently than I thought it would.
That will be fixed in a few days.

**Comment by kyubuns** [comment]
It was a simple mistake on my part.
Please update to `ac66aaf42e513b9d5c81f3f1dc6cd1969aa1d27f`.

Only when a GameObject's name is not unique, the correct behavior is to name the parent until it becomes unique.

Example: The name "Text" is not unique and will be given the name of the parent.
<img width="157" alt="Screen Shot 2020-09-25 at 14 28 58" src="https://user-images.githubusercontent.com/961165/94229794-7471f480-ff3b-11ea-9b4a-d8ae7ca7ace4.png">
```csharp
public Button HogeButton { get; private set; }
public Text HogeButtonText { get; private set; }
public Button SomeButton { get; private set; }
public Text SomeButtonText { get; private set; }
public Button PiyoButton { get; private set; }
public Text PiyoButtonText { get; private set; }
```
